POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:findAllInventories>
            
        </jets:findAllInventories>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:getInventoriesPage>
            <page>2</page>
            <limit>4</limit>
        </jets:getInventoriesPage>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:findInventoryById>
            <id>1</id>
        </jets:findInventoryById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:addInventory>
     <Inventory>
        <lastUpdate>2006-02-15T04:09:17+02:00</lastUpdate>
        <filmId>
          <lastUpdate>2023-04-17T04:36:33+02:00</lastUpdate>
          <description>A Epic Dramaa of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies</description>
          <filmId>2</filmId>
          <releaseYear>2006</releaseYear>
          <title>ACADEMY DINOSAUR</title>
        </filmId>
        <storeId>
          <lastUpdate>2023-04-17T04:42:59+02:00</lastUpdate>
          <storeId>2</storeId>
        </storeId>
      </Inventory>
        </jets:addInventory>
    </soap:Body>
</soap:Envelope>
###
POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:updateInventory>
            <id>1</id>
        
      <Inventory>
        <lastUpdate>2006-02-15T04:09:17+02:00</lastUpdate>
        <filmId>
          <lastUpdate>2023-04-17T04:36:33+02:00</lastUpdate>
          <description>A Epic Dramaa of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies</description>
          <filmId>1</filmId>
          <releaseYear>2006</releaseYear>
          <title>ACADEMY DINOSAUR</title>
        </filmId>
        <inventoryId>1</inventoryId>
        <storeId>
          <lastUpdate>2023-04-17T04:42:59+02:00</lastUpdate>
          <storeId>2</storeId>
        </storeId>
      </Inventory>
      
        </jets:updateInventory>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9090/sakila-soap/ws/inventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:deleteInventoryById>
            <id>4584</id>
        </jets:deleteInventoryById>
    </soap:Body>
</soap:Envelope>
