POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:findAllStaffs>
            
        </jets:findAllStaffs>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:getStaffsPage>
            <page>1</page>
            <limit>4</limit>
        </jets:getStaffsPage>
    </soap:Body>
  </soap:Envelope>

###

POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:getStaffPicture>
            <id>1</id>
        </jets:getStaffPicture>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:findStaffById>
            <id>1</id>
        </jets:findStaffById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:addStaff>
     
           <staff>
        <lastUpdate>2006-02-15T02:57:16+02:00</lastUpdate>
        <active>true</active>
        <addressId>
          <lastUpdate>2014-09-25T22:30:27+03:00</lastUpdate>
          <address>23 Workhaven Lane</address>
          <addressId>3</addressId>
          <cityId>
            <lastUpdate>2006-02-15T03:45:25+02:00</lastUpdate>
            <city>Lethbridge</city>
            <cityId>300</cityId>
            <countryId>
              <lastUpdate>2006-02-15T03:44:00+02:00</lastUpdate>
              <country>Canada</country>
              <countryId>20</countryId>
            </countryId>
          </cityId>
          <district>Alberta</district>
          <location>AAAAAAEBAAAAzcQZaGM0XMAd7n5wmdlIQA==</location>
          <phone>14033335568</phone>
          <postalCode></postalCode>
        </addressId>
        <email>Mike.Hillyer@sakilastaff.com</email>
        <firstName>Mike</firstName>
        <lastName>Hillyer</lastName>
        <password>8cb2237d0679ca88db6464eac60da96345513964</password>
        <storeId>
          <lastUpdate>2023-04-17T04:42:59+02:00</lastUpdate>
          <storeId>2</storeId>
        </storeId>
        <username>aa</username>
      </staff>
        </jets:addStaff>
    </soap:Body>
</soap:Envelope>
###
POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:updateStaff>
            <id>6</id>
         <staff>
        <lastUpdate>2023-04-17T13:08:01.154+02:00</lastUpdate>
        <active>true</active>
        <addressId>
          <lastUpdate>2014-09-25T22:30:27+03:00</lastUpdate>
          <address>23 Workhaven Lane</address>
          <addressId>3</addressId>
          <cityId>
            <lastUpdate>2006-02-15T03:45:25+02:00</lastUpdate>
            <city>Lethbridge</city>
            <cityId>300</cityId>
            <countryId>
              <lastUpdate>2006-02-15T03:44:00+02:00</lastUpdate>
              <country>Canada</country>
              <countryId>20</countryId>
            </countryId>
          </cityId>
          <district>Alberta</district>
          <location>AAAAAAEBAAAAzcQZaGM0XMAd7n5wmdlIQA==</location>
          <phone>14033335568</phone>
          <postalCode></postalCode>
        </addressId>
        <email>Mike.Hillyer@sakilastaff.com</email>
        <firstName>Mike</firstName>
        <lastName>Hillyer</lastName>
        <password>8cb2237d0679ca88db6464eac60da96345513964</password>
        <staffId>6</staffId>
        <storeId>
          <lastUpdate>2023-04-17T04:42:59+02:00</lastUpdate>
          <storeId>1</storeId>
        </storeId>
        <username>bb</username>
      </staff>
        </jets:updateStaff>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:9090/sakila-soap/ws/staff HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://webService.jets.iti.gov/">
    <soap:Body>
        <jets:deleteStaffById>
            <id>6</id>
        </jets:deleteStaffById>
    </soap:Body>
</soap:Envelope>